mysite/urls.py
from django.contrib import admin
from django.urls import path, include
import polls.views as views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('reset/', views.reset_index, name='reset_index'),
    path('reset/<int:question_id>/', views.reset, name='reset_votes'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def total_votes(self):
        """ Return the total number of votes for this poll question."""
        count_votes = 0
        for choice in self.choice_set.all():
            count_votes += choice.votes
        return count_votes

    def reset_votes(self):
        """ Resets the vote count to zero for all Choice for the Question."""
        for choice in self.choice_set.all():
            choice.votes = 0
            choice.save()
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/models/choice.py
from django.db import models
from polls.models.question import Question


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

    @property
    def total_votes(self):
        return self.vote_set.count()

polls/models/question.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def total_votes(self):
        """ Return the total number of votes for this poll question."""
        count_votes = 0
        for choice in self.choice_set.all():
            count_votes += choice.total_votes
        return count_votes

    def reset_votes(self):
        """ Resets the vote count to zero for all Choice for the Question."""
        for choice in self.choice_set.all():
            for vote in choice.vote_set.all():
                vote.delete()
            choice.save()

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

polls/models/vote.py
from django.db import models
from polls.models.question import Question
from polls.models.choice import Choice
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


class Vote(models.Model):
    """ A vote by a user """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from polls.models.question import Question
from polls.models.choice import Choice
from polls.models.vote import Vote


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        find_vote = Vote.objects.filter(question=question, user=request.user)
        if find_vote.count() != 0:
            for user_vote in find_vote:
                user_vote.delete()
        new_vote = selected_choice.vote_set.create(question=question, choice=selected_choice, user=request.user)
        new_vote.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def reset_index(request):
    all_question_list = Question.objects.all()
    context = {'all_question_list': all_question_list}
    return render(request, 'polls/reset_polls.html', context)


def reset(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.reset_votes()
    messages.success(request, f'Reset votes for Poll \"{question.question_text}"')
    return HttpResponseRedirect(reverse('polls:reset_index'))

polls/templates/components/base.html
{% extends 'components/navbar.html' %}
{% load sass_tags %}

{% block header %}
    <!DOCTYPE html>
    <html lang="en">
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Django Polls</title>

        {#    Vue.js    #}
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        {#    Font Awesome    #}
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
        {#    Bulma.sass    #}
        <link rel="stylesheet" href="{% sass_src 'vendor/bulma/bulma.sass' %}">
        <link rel="stylesheet" href="{% sass_src 'components/radio.sass' %}">
    </head>
    <body>
{% endblock %}

{% block body %}

    <div id="app">
        {% block content %}
        {% endblock  %}
    </div>

{% endblock %}

{% block footer %}
</body>
    <script>
        var app = new Vue(){
            el: '#app',
        }
    </script>
</html>
{% endblock %}

polls/templates/components/navbar.html
{% block header %}
{% endblock %}

<nav class="navbar" role="navigation" aria-label="main navigation">
<div class="navbar-brand">

<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
  <span aria-hidden="true"></span>
</a>
</div>

<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <a class="navbar-item" href="{% url 'polls:index' %}">
    Home
  </a>
  </div>
</div>

    {% if not user.is_authenticated %}
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light" href="{% url 'login' %}?next={{ request.path }}">
                Log in
              </a>
            </div>
          </div>
        </div>
    {% else %}
        <div class="navbar-end">
            <div class="navbar-item">
                <a class="button is-info is-outlined" href="{% url 'logout' %}?next={{ request.path }}">Log out</a>
            </div>
        </div>
    {% endif %}


</div>
</nav>

{% block body %}
{% endblock %}

{% block footer %}
{% endblock %}

polls/templates/polls/detail.html
{% extends 'components/base.html' %}
{% load filter %}

{% block content %}
    <div class="hero">

    </div>

    <section class="hero is-info is-bold">
        <div class="hero-body">
            <h2 class="title is-2">{{ question.question_text }}</h2>
            {% if user.is_authenticated %}
                <p class="subtitle">Welcome back, {{ user.username.title }}</p>
            {% else %}
                <p class="subtitle">
                    Please <a class="button is-info is-inverted is-small is-outlined"
                              href="{% url 'login' %}?next={{ request.path }}">login
                    </a> to vote for a topic.
                </p>
            {% endif %}
        </div>
    </section>

    <section class="section">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <div class="field">
            <form action="{% url 'polls:vote' question.id %}" method="post" id="choice">
                {% csrf_token %}
                    {% for choice in question.choice_set.all %}
                        <div class="inputGroup">
                            {% if choice|check_votes:user == 0 %}
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            {% else %}
                                <input type="radio" checked="checked" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            {% endif %}
                            <label class="radioChoice" for="choice{{ forloop.counter }}">
                                {{ choice.choice_text }}
                            </label>
                        </div>
                    {% endfor %}
                <dev class="buttons section">
                    <input class="button is-info" type="submit" value="Vote" id="voteButton">
                    <a class="button" href="{% url 'polls:index' %}">Back to polls</a>
                    <a class="button" href="{% url 'polls:results' question.id %}">See the results</a>
                </dev>
            </form>
        </div>
    </section>


{% endblock %}

polls/templates/polls/index.html
{% extends 'components/base.html' %}


{% block content %}
    <section class="hero is-info is-bold">
        <div class="hero-body">
            <h2 class="title is-2" id="my_title">Hot Topics</h2>
            {% if user.is_authenticated %}
                <p class="subtitle">Welcome back, {{ user.username.title }}</p>
            {% else %}
                <p class="subtitle">
                    Please <a class="button is-info is-inverted is-small is-outlined"
                              href="{% url 'login' %}?next={{ request.path }}">login
                    </a> to vote for a topic.
                </p>
            {% endif %}
        </div>
    </section>

    <section class="section">
        <div class="container" id="question-container">
            {% if latest_question_list %}
                <div class="buttons">
                {% for question in latest_question_list %}
                <a class="button is-fullwidth is-info is-outlined is-rounded question"
                   id="questionId{{ question.id }}"
                   href="{% url 'polls:detail' question.id %}">
                    {{ question.question_text }}
                </a>
                {% endfor %}
                </div>
            {% else %}
                <p id="no-polls">No polls are available.</p>
            {% endif %}
        </div>
    </section>

{% endblock %}

polls/templates/polls/reset_polls.html
<html>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>Reset Polls Voting</h1>


<table>
  <tr>
  <th>Poll</th> <th>Total Votes</th> <th>Reset Votes?</th>
  </tr>
  <!-- body of table -->
    {% for question in all_question_list %}
      <tr>
        <td><a href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a></td>
        <td align="center">{{ question.total_votes }}</td>
          {% ifnotequal question.total_votes 0 %}
            {% csrf_token %}
            <td align="center"><a href="{% url 'polls:reset_votes' question.id %}">Reset Votes</a></td>
          {% else %}
              <td align="center">No Votes</td>
          {% endifnotequal %}
      </tr>
    {% endfor %}
</table>

{% if messages %}
   <!-- display messages here -->
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

</body>
</html>

polls/templates/polls/results.html
{% extends 'components/base.html' %}

{% block content %}
<section class="hero is-info is-bold">
    <div class="hero-body">
        <h2 class="title is-2">{{ question.question_text }}</h2>
    </div>
</section>

<div class="container">
    <section class="section">
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.total_votes }} vote{{ choice.total_votes|pluralize }}</li>
        {% endfor %}
        </ul>

        <div class="buttons">
            <a class="button" href="{% url 'polls:detail' question.id %}">Vote again?</a>
            <a class="button" href="{% url 'polls:index' %}">Back to List of Polls</a>
            {% if user.is_authenticated %}
                <a class="button" href="{% url 'logout' %}">logout</a>
            {% endif %}
        </div>
    </section>
</div>


{% endblock %}